### PR TITLE
Add Citation Section in README.me

### PR DESCRIPTION
**Pull request by rlebret**
## Description

Add bibtex of MoZuMa paper from MM'22 at the end of the README.md

### CODE REVIEW

**Comment by smassonnet** [comment]
@rlebret , I was thinking about this as well. We could also add it the ["GitHub's way"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

**Comment by rlebret** [comment]
Yes, it makes sense. I didn't know about GitHub's way 😄 
I will do the changes.

**Comment by rlebret** [comment]
@smassonnet I've added `CITATION.cff`. It produces the correct bibtex when copying from the citation button.
I think that we should keep the citation section at the bottom of `README.md` as some people may not know about GitHub's citation button.

**Review by smassonnet — APPROVED** [review]
Looks good !

**Pull request merged**
